README.md, src/createLogger.js
Fixes #3 by adding an option to pass a custom logger implementation instead of `console`
=> Support custom loggers

README.md
I had to search the code to see what the default values for the options are. 
So others don't have to do that, I added them to the README. I think it also helps to understand the options a little bit better.
=> Added default values to README

build/createLogger.js, src/createLogger.js
I've been working on an app where we're using Symbols as the action types.  Using redux-logger in this case throws an exception since Symbol doesn't support string concatenation.  So this small patch manually coerces the action type to a string before attempting to log it.
=> Add support for Symbol action types

README.md, build/createLogger.js, src/createLogger.js
generic solution for #7
usage with Immutable
```
const logger = createLogger({
transformer: state => state && state.toJS()
});
```
=> added state transformer (allows better immutable logging)

README.md
Property name `transformer` in the README now matches the code.
=> fix typo in transformer option documentation

README.md, build/createLogger.js, src/createLogger.js
* Added `timestamp` (default `true`) option to disable timestamp printing.
* Pad numbers with zeros in timestamp (e.g. `1:8:5` becomes `1:08:05`).
=> Add timestamp option + pad hours/minutes

README.md
I updated the README per comments in #22 and I've verified.
Only state from the first reducer is logged, so this did not perform as expected when there were multiple reducers.  This patch fixes that issue per feedback from @alakiikonen.
=> fix patch for immutable transform example when there are multiple reducers

README.md, src/createLogger.js
Nice for small performance debugging.
=> Log action durations

README.md, src/createLogger.js, src/logger.js
This way collapsed can take a function like predicate to specify which actions should be collapsed. Or it take a boolean as before. Also put collapsed and predicate next to each other in the docs because of their new similarities.
=> Collapsed can take function

src/index.js
Must be called on console itself, otherwise it doesn’t work.
=> Fix collapsed option

src/index.js
Looks like Mobile Safari / Chrome don't support `String.prototype.repeat`. I think this is an issue on iOS 8 and not iOS 9, but it'd be good just to make this more cross browser compatible.
=> fix for mobile

README.md
add import of `applyMiddleware` to show readers where it comes from.
=> add import applyMiddleware from redux in README

src/index.js
```diff
const started = timer.now();
const prevState = stateTransformer(getState());
const formattedAction = actionTransformer(action);
+   const returnedValue = next(action);
const took = timer.now() - started;
const nextState = stateTransformer(getState());
-   return next(action);
+   return returnedValue;
```
prevState and nextState is same because `next(action)` doesn't get executed between prevState and nextState.
This pull request fixes the problem by putting `next(action)` between them.
=> fix: prevState and nextState being same

src/index.js
When configuring the middleware with the following option object:
````
{
collapsed: true,
stateTransformer: stateToJS,
}
```
It will log `action MY_ACTION_NAME @ 17:20:39.566false`. Same thing if manually disabling the timestamp (`timestamp: false`). This commit should fix that.
If you'd prefer to do it otherwise, let me know, I'll update the PR :)
=> Remove log of 'false' when timestamp or duration logging disabled

README.md, src/index.js
This is something I've found really useful, I collapse all log items and can see errors at a glance, without opening up groups. Also handy for coloring pending/fetching actions.
=> Add titleStyle option for adding CSS to title text

src/index.js
When an error is thrown during action execution (possibly meaning in listeners executed in reaction), the action should be logged to help with debugging.
=> Logging of crashed actions

src/index.js
When redux dispatch an action, after calling the reducer, the listeners
will be called. If the listener dispatch a new action, redux allow it,
but the order of the log will in reverse.
this PR fix the order in that case.
=> fix logger order

src/index.js
Here's a fix for #114. I was not able to run the tests, I got this issue:
```
~/s/redux-logger (master) $ npm test
> redux-logger@2.3.1 test /Users/ericcapps/src/redux-logger
> npm run lint
> redux-logger@2.3.1 lint /Users/ericcapps/src/redux-logger
> $(npm bin)/eslint src
sh: /Users/ericcapps/src/redux-logger/node_modules/.bin/eslint: No such file or directory
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! redux-logger@2.3.1 lint: `$(npm bin)/eslint src`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the redux-logger@2.3.1 lint script '$(npm bin)/eslint src'.
npm ERR! This is most likely a problem with …
```
=> Fix a bug where next state was not logged when an error was logged

src/index.js
Assuming the existence of window means redux-logger cannot be used in universal applications. 
This removes the dependency on window being the global variable.
=> remove window

src/index.js
Fixed a bug where `Date()` was being passed a timer value from `performance.now()` instead of a proper date/time.
=> Fixed timestamp bug

README.md, example/src/index.js, src/index.js
fix #94
fix #54
This PR would allow to have a fine grained control on the level of each part of the log (useful if you want the action to be an error to be able to see the stack trace for example).
=> fine grained level

src/defaults.js
Since dev tools are just an HTML page, inherit the console's default color.
This fixes unreadable text in Chrome DevTools when the Dark theme is selected.
=> Set title to color to inherit

src/defaults.js
It breaks in IE9 when the package is just required.
=> Check for console

src/core.js
When disabling the timestamp you currently get the following
`action @  actionType`
The `@` is still present and there are two spaces between it and the action type (multiple spaces don't appear to render on github)
=> update default title formatter

src/defaults.js
This PR fixes a `ReferenceError: window is not defined` error which is thrown when running outside of a browser (e.g. node).
This broke in https://github.com/evgenyrodionov/redux-logger/pull/185/commits/b708f568ac2cd99b139c0865411da3cd855e4b03
=> fix 'window is not defined' error in node

src/diff.js
I noticed when I enabled diffs that I was getting `[object Object]` in the diffs. I made this change so that instead of stringifying the output from `deep-diff`, the values are sent directly to `logger.log`.
I don't know about `console` implementations outside of Chrome, but Chrome's console works great at displaying the objects in a nice format for inspection.
=> Log diff output directly instead of converting to string

README.md, src/core.js
so that I can implement a collapse function that collapses everything but entries with errors
=> feat(core.js): pass logEntry to collapsed function

package.json, spec/index.spec.js, src/index.js
I wrote a few tests for this behavior: @evgenyrodionov let me know if you'd like to see this behavior tested in a different way.
Closes #160
=> Error if createLogger is passed to applyMiddleware

src/core.js
=> Change date position. Set lighter font for groups

src/core.js
=> ignore color formatting with custom titleFormatter

src/index.js
Update comment to match what told in deprecation warnin 
`Since 3.0.0 redux-logger exports by default logger with default settings.`
=> Update comment to match implementation

src/core.js
@evgenyrodionov, let me know if you'd like to see this done differently. We could also do a `try/catch` and print the stack trace, but this seems cleaner for most browsers (ie. Chrome). Here's a gif of how it looks:
We could also make this opt-in if you'd prefer. Let me know! 👍 
Closes #158
=> Add trace for supported loggers

package.json, src/core.js
When I pulled the latest code and ran `yarn`. It failed linting
- Fixed the issue
- Added `npm run lint` to `precommit` and `prepublish` scripts to prevent this from occurring in the future
=> fix lint issue and add lint on pre-commit/build

package.json, rollup.config.js
That should close #233.
But needs testing to prevent #229 and #231 to happen again.
=> `umd` and `es` targets instead of import source
